# Generated by Django 3.1.6 on 2021-02-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrateur',
            new_name='Administrateurs',
        ),
    ]
