# Generated by Django 3.1.6 on 2021-02-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20210202_1437'),
        ('administrateurs', '0002_auto_20210202_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateurs',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrateurs',
            name='telephone',
            field=models.IntegerField(error_messages={'unique': 'Le téléphone saisi est déjà utilisé.'}, unique=True),
        ),
    ]
