# Generated by Django 3.1.6 on 2021-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0003_auto_20210202_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateurs',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
