# Generated by Django 3.1.6 on 2021-02-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrateurs', '0004_auto_20210203_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateurs',
            name='adr_mail',
        ),
        migrations.RemoveField(
            model_name='administrateurs',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='administrateurs',
            name='password',
        ),
        migrations.AddField(
            model_name='administrateurs',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
