# Generated by Django 3.1.6 on 2021-02-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0007_auto_20210208_1420'),
        ('administrateurs', '0006_auto_20210208_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAffaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(error_messages={'unique': 'Le nom saisi existe déjà.'}, max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=8, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrateurs.administrateurs')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations')),
            ],
        ),
    ]
