# Generated by Django 3.1.4 on 2021-04-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points_affaire', '0002_pointsaffaires_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsaffaires',
            old_name='telephone',
            new_name='telephone_point',
        ),
    ]
