# Generated by Django 3.1 on 2021-06-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerants', '0001_initial'),
        ('services', '0004_services_date_add'),
        ('points_affaire', '0003_auto_20210408_1045'),
        ('clients', '0008_auto_20210407_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prestation', models.DateTimeField(auto_now_add=True)),
                ('montant_prestation', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients')),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerants.utilisateurs')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='points_affaire.pointsaffaires')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prestation.prestations')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services')),
            ],
        ),
        migrations.AddField(
            model_name='prestations',
            name='service',
            field=models.ManyToManyField(through='prestation.ServicePrestation', to='services.Services'),
        ),
    ]
