# Generated by Django 3.1 on 2021-07-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210407_1541'),
        ('prestation', '0005_auto_20210707_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestations',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients'),
        ),
    ]
