# Generated by Django 3.1 on 2021-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_affaire', '0003_auto_20210408_1045'),
        ('services', '0004_services_date_add'),
        ('prestation', '0006_auto_20210708_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestations',
            name='point_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points_affaire.pointsaffaires'),
        ),
        migrations.AlterField(
            model_name='serviceprestation',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestation.prestations'),
        ),
        migrations.AlterField(
            model_name='serviceprestation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services'),
        ),
    ]
