# Generated by Django 3.1.6 on 2021-02-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0007_auto_20210208_1420'),
        ('points_affaire', '0001_initial'),
        ('categories', '0003_categories_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(error_messages={'unique': 'Le service existe déjà.'}, max_length=35, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations')),
                ('point_vente', models.ManyToManyField(to='points_affaire.PointsAffaires')),
            ],
        ),
    ]
