# Generated by Django 3.1.4 on 2021-04-12 14:34

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210302_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
