# Generated by Django 3.1 on 2021-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_admin'),
        ('services', '0004_services_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories'),
        ),
    ]
