# Generated by Django 3.1 on 2022-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210712_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='nom',
            field=models.CharField(max_length=35),
        ),
    ]
