# Generated by Django 3.1.6 on 2021-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='adr_mail',
            field=models.EmailField(max_length=255),
        ),
    ]
