# Generated by Django 3.1.6 on 2021-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210302_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='telephone',
            new_name='telephone_p',
        ),
        migrations.AddField(
            model_name='clients',
            name='telephone_s',
            field=models.CharField(error_messages={'unique': 'Le téléphone saisi existe déjà!'}, max_length=8, null=True, unique=True),
        ),
    ]
