# Generated by Django 3.1.4 on 2021-04-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clients_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='org',
        ),
    ]
