# Generated by Django 3.1.4 on 2021-04-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20210208_1420'),
        ('clients', '0006_remove_clients_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.organisations'),
            preserve_default=False,
        ),
    ]
