# Generated by Django 3.1.4 on 2021-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clients_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='telephone_s',
            field=models.CharField(blank=True, error_messages={'unique': 'Le téléphone saisi existe déjà!'}, max_length=8, null=True),
        ),
    ]
