# Generated by Django 3.1 on 2022-11-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210712_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='adr_mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='adr_phisique',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
