# Generated by Django 3.1.6 on 2021-02-16 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrateurs', '0006_auto_20210208_1409'),
        ('points_affaire', '0001_initial'),
        ('organisations', '0007_auto_20210208_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(error_messages={'unique': 'Le téléphone saisi est déjà utilisé.'}, max_length=8, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrateurs.administrateurs')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points_affaire.pointsaffaires')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
