# Generated by Django 3.1.6 on 2021-02-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0006_auto_20210208_1409'),
        ('categories', '0002_categories_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrateurs.administrateurs'),
            preserve_default=False,
        ),
    ]
