# Generated by Django 3.1 on 2022-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='nom',
            field=models.CharField(max_length=55),
        ),
    ]
