# Generated by Django 3.1 on 2021-06-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points_affaire', '0003_auto_20210408_1045'),
        ('produits', '0011_auto_20210519_1723'),
        ('gerants', '0001_initial'),
        ('clients', '0008_auto_20210407_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_cmdee', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_brut', models.FloatField()),
                ('montant_net', models.FloatField()),
                ('taxe', models.FloatField()),
                ('taux_taxe', models.IntegerField(default=18)),
                ('remise', models.FloatField(null=True)),
                ('taux_remise', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients')),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerants.utilisateurs')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='points_affaire.pointsaffaires')),
                ('produit', models.ManyToManyField(through='ventess.ProduitVente', to='produits.Produits')),
            ],
        ),
        migrations.AddField(
            model_name='produitvente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventess.ventes'),
        ),
    ]
