# Generated by Django 3.1 on 2021-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventes',
            name='net_ccial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
