# Generated by Django 3.1 on 2021-06-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_auto_20210519_1723'),
        ('points_affaire', '0003_auto_20210408_1045'),
        ('gerants', '0001_initial'),
        ('ventess', '0002_ventes_net_ccial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoProdVte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gerants.utilisateurs')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='points_affaire.pointsaffaires')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produits.produits')),
            ],
        ),
    ]
