# Generated by Django 3.1 on 2021-07-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_auto_20210519_1723'),
        ('ventess', '0008_auto_20210708_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitvente',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produits'),
        ),
        migrations.AlterField(
            model_name='produitvente',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventess.ventes'),
        ),
    ]
