# Generated by Django 3.1 on 2021-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_affaire', '0003_auto_20210408_1045'),
        ('produits', '0012_auto_20210712_1010'),
        ('ventess', '0009_auto_20210708_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histoprodvte',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points_affaire.pointsaffaires'),
        ),
        migrations.AlterField(
            model_name='histoprodvte',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produits'),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='point_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points_affaire.pointsaffaires'),
        ),
    ]
