# Generated by Django 3.1.4 on 2021-03-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0006_auto_20210302_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_ajoutee', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='produits.produits')),
            ],
        ),
    ]
