# Generated by Django 3.1.4 on 2021-05-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histo_prod', '0003_auto_20210315_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriqueProd',
        ),
    ]
