# Generated by Django 3.0.7 on 2021-01-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisations',
            old_name='date',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='organisations',
            old_name='telephone',
            new_name='telephone_p',
        ),
        migrations.AddField(
            model_name='organisations',
            name='telephone_s',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
