# Generated by Django 3.0.7 on 2021-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20210128_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='telephone_p',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_s',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
