# Generated by Django 3.0.7 on 2021-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20210129_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='mail',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_p',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_s',
            field=models.IntegerField(max_length=8, null=True, unique=True),
        ),
    ]
