# Generated by Django 3.1.6 on 2021-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20210129_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='mail',
            field=models.CharField(error_messages={'unique': 'Une organisation avec cette adresse mail déjà.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='nom',
            field=models.CharField(error_messages={'unique': 'Une organisation avec ce nom existe déjà.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_p',
            field=models.IntegerField(error_messages={'unique': 'Une organisation avec ce nom téléphone déjà.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_s',
            field=models.IntegerField(error_messages={'unique': 'Une organisation avec ce nom téléphone déjà.'}, null=True, unique=True),
        ),
    ]
