# Generated by Django 3.1 on 2021-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20210208_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='telephone_p',
            field=models.CharField(error_messages={'unique': 'Une organisation avec ce téléphone déjà.'}, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='telephone_s',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
