# Generated by Django 3.1 on 2021-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20210815_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='telephone_s',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
