# Generated by Django 3.1.6 on 2021-02-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateurs', '0006_auto_20210208_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(error_messages={'unique': 'Le produit saisi existe déjà.'}, max_length=255, unique=True)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrateurs.administrateurs')),
            ],
        ),
    ]
