# Generated by Django 3.1.6 on 2021-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_affaire', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='point_vente',
            field=models.ManyToManyField(to='points_affaire.PointsAffaires'),
        ),
    ]
