# Generated by Django 3.1.6 on 2021-02-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('produits', '0002_produits_point_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produits',
            name='image',
            field=models.ImageField(null=True, upload_to='products_img/'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='designation',
            field=models.CharField(error_messages={'unique': 'Le produit saisi existe déjà.'}, max_length=100, unique=True),
        ),
    ]
