# Generated by Django 3.1.6 on 2021-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_auto_20210212_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_img/'),
        ),
    ]
