# Generated by Django 3.1.6 on 2021-02-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20210208_1420'),
        ('produits', '0004_auto_20210215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations'),
            preserve_default=False,
        ),
    ]
