# Generated by Django 3.1.6 on 2021-03-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_admin'),
        ('produits', '0005_produits_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categories'),
        ),
    ]
