# Generated by Django 3.1.4 on 2021-04-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_auto_20210302_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='point_vente',
        ),
    ]
