# Generated by Django 3.1.4 on 2021-04-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_affaire', '0003_auto_20210408_1045'),
        ('produits', '0007_remove_produits_point_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_stock', models.IntegerField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='points_affaire.pointsaffaires')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produits.produits')),
            ],
        ),
        migrations.AddField(
            model_name='produits',
            name='point_vente',
            field=models.ManyToManyField(through='produits.QuantitePoint', to='points_affaire.PointsAffaires'),
        ),
    ]
