# Generated by Django 3.1.4 on 2021-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_auto_20210414_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='quantite',
        ),
    ]
