# Generated by Django 3.1.4 on 2021-05-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_histoprod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histoprod',
            old_name='qte_entrante',
            new_name='qte',
        ),
    ]
