# Generated by Django 3.1 on 2021-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_admin'),
        ('points_affaire', '0003_auto_20210408_1045'),
        ('produits', '0011_auto_20210519_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histoprod',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points_affaire.pointsaffaires'),
        ),
        migrations.AlterField(
            model_name='histoprod',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produits'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='quantitepoint',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points_affaire.pointsaffaires'),
        ),
        migrations.AlterField(
            model_name='quantitepoint',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produits'),
        ),
    ]
