# Generated by Django 3.1 on 2022-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_auto_20210712_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
